#!/bin/bash

# Google Scraper - Test Commands & Curl Examples
# Run these to test the newly activated Google Scraper

# Set your admin token here
ADMIN_TOKEN="your_admin_token_here"
BASE_URL="http://localhost:8000/api/v1"

echo "=================================================="
echo "GOOGLE SCRAPER TEST COMMANDS"
echo "=================================================="
echo ""

# Test 1: Check if scheduler is running
echo "1️⃣  CHECK SCHEDULER STATUS"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X GET \"$BASE_URL/google-scraping/scheduler-status\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Expected Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"scheduler_status\": {"
echo "    \"scheduler_running\": true,"
echo "    \"job_configured\": true,"
echo "    \"job_next_run\": \"2025-04-30T02:00:00+00:00\","
echo "    \"consecutive_failures\": 0,"
echo "    \"markets_count\": 20"
echo "  }"
echo "}"
echo ""
echo ""

# Test 2: Get last scrape results
echo "2️⃣  GET LAST SCRAPE RESULTS"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X GET \"$BASE_URL/google-scraping/scrape-results\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Expected Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"timestamp\": \"2025-04-29T02:00:15.123Z\","
echo "  \"total_businesses_found\": 1250,"
echo "  \"total_signals_written\": 3420,"
echo "  \"duration_seconds\": 245.5,"
echo "  \"failed_markets_count\": 0,"
echo "  \"failed_markets\": [],"
echo "  \"markets\": { ... }"
echo "}"
echo ""
echo ""

# Test 3: Manually trigger scrape
echo "3️⃣  MANUALLY TRIGGER SCRAPE (BACKGROUND)"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X POST \"$BASE_URL/google-scraping/trigger-scrape\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\""
echo ""
echo "Expected Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"message\": \"Scrape triggered in background\","
echo "  \"admin_id\": 123,"
echo "  \"timestamp\": \"2025-04-29T22:55:00.000Z\""
echo "}"
echo ""
echo "Note: Scrape runs in background. Check /scrape-results endpoint after 4-6 minutes"
echo ""
echo ""

# Test 4: View jobs
echo "4️⃣  VIEW ALL SCRAPE JOBS"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X GET \"$BASE_URL/google-scraping/jobs?limit=10\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Expected Response:"
echo "["
echo "  {"
echo "    \"id\": 1,"
echo "    \"name\": \"Daily Scrape - New York, NY\","
echo "    \"status\": \"completed\","
echo "    \"total_found\": 145,"
echo "    \"started_at\": \"2025-04-29T02:00:15.123Z\","
echo "    \"completed_at\": \"2025-04-29T02:05:30.456Z\""
echo "  },"
echo "  ..."
echo "]"
echo ""
echo ""

# Test 5: Get platform stats
echo "5️⃣  GET GOOGLE SCRAPING STATS"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X GET \"$BASE_URL/google-scraping/stats\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Expected Response:"
echo "{"
echo "  \"total_locations\": 20,"
echo "  \"total_keyword_groups\": 5,"
echo "  \"total_jobs\": 120,"
echo "  \"completed_jobs\": 95,"
echo "  \"cached_businesses\": 8500"
echo "}"
echo ""
echo ""

# Test 6: Seed locations (if needed)
echo "6️⃣  SEED LOCATIONS (ONE-TIME)"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X POST \"$BASE_URL/google-scraping/locations/seed\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"added\": 20,"
echo "  \"skipped\": 0,"
echo "  \"total\": 20"
echo "}"
echo ""
echo ""

# Test 7: Seed keywords (if needed)
echo "7️⃣  SEED KEYWORDS (ONE-TIME)"
echo "=================================================="
echo ""
echo "Command:"
echo "curl -X POST \"$BASE_URL/google-scraping/keyword-groups/seed\" \\"
echo "  -H \"Authorization: Bearer $ADMIN_TOKEN\""
echo ""
echo "Response:"
echo "{"
echo "  \"success\": true,"
echo "  \"added\": 10,"
echo "  \"skipped\": 5,"
echo "  \"total\": 15"
echo "}"
echo ""
echo ""

# Actual runnable commands
echo ""
echo "=================================================="
echo "READY-TO-RUN COMMANDS (Update ADMIN_TOKEN first)"
echo "=================================================="
echo ""
echo "# Copy & paste these:"
echo ""
echo "export ADMIN_TOKEN='your_admin_token_here'"
echo "export BASE_URL='http://localhost:8000/api/v1'"
echo ""
echo "# 1. Check scheduler"
echo "curl -X GET \"\$BASE_URL/google-scraping/scheduler-status\" -H \"Authorization: Bearer \$ADMIN_TOKEN\" | jq ."
echo ""
echo "# 2. Get results"
echo "curl -X GET \"\$BASE_URL/google-scraping/scrape-results\" -H \"Authorization: Bearer \$ADMIN_TOKEN\" | jq ."
echo ""
echo "# 3. Trigger scrape"
echo "curl -X POST \"\$BASE_URL/google-scraping/trigger-scrape\" -H \"Authorization: Bearer \$ADMIN_TOKEN\" | jq ."
echo ""
echo "# 4. View jobs"
echo "curl -X GET \"\$BASE_URL/google-scraping/jobs?limit=5\" -H \"Authorization: Bearer \$ADMIN_TOKEN\" | jq ."
echo ""
echo "# 5. Get stats"
echo "curl -X GET \"\$BASE_URL/google-scraping/stats\" -H \"Authorization: Bearer \$ADMIN_TOKEN\" | jq ."
echo ""
