from sqlalchemy import Column, Integer, String, DateTime, Text, Float, ForeignKey, Boolean, Enum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.db.database import Base
import enum


class RealmType(enum.Enum):
    physical = "physical"
    digital = "digital"
    both = "both"


class Opportunity(Base):
    __tablename__ = "opportunities"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String(500), nullable=False, index=True)
    description = Column(Text, nullable=False)

    # Realm Type (Physical/Digital/Both)
    realm_type = Column(String(20), default="both", index=True)

    # Categorization
    category = Column(String(100), nullable=False, index=True)
    subcategory = Column(String(100), nullable=True)

    # Metrics
    severity = Column(Integer, nullable=False)  # 1-5 scale
    validation_count = Column(Integer, default=0)
    growth_rate = Column(Float, default=0.0)  # Week-over-week percentage
    market_size = Column(String(50), nullable=True)  # e.g., "$10M-$100M"

    # Geographic Information
    geographic_scope = Column(String(50), default="online")  # local, regional, national, international, online
    country = Column(String(100), nullable=True)  # Country name or code
    region = Column(String(100), nullable=True)  # State/Province/Region
    state = Column(String(100), nullable=True)   # Two-letter state abbreviation
    city = Column(String(100), nullable=True)  # City name
    latitude = Column(Float, nullable=True)  # GPS latitude
    longitude = Column(Float, nullable=True)  # GPS longitude

    # Completion Tracking
    completion_status = Column(String(50), default="open")  # open, in_progress, solved, abandoned
    solution_description = Column(Text, nullable=True)  # Description of solution if solved
    solved_at = Column(DateTime(timezone=True), nullable=True)  # When was it solved
    solved_by = Column(String(255), nullable=True)  # Company/person who solved it

    # Feasibility Metrics
    feasibility_score = Column(Float, nullable=True)  # Calculated feasibility score (0-100)
    duplicate_of = Column(Integer, ForeignKey("opportunities.id"), nullable=True)  # Link to original if duplicate

    # Author
    author_id = Column(Integer, ForeignKey("users.id"), nullable=True)
    is_anonymous = Column(Boolean, default=False)

    # Status
    status = Column(String(50), default="active")  # active, resolved, archived
    
    # Moderation Status (for admin quality control)
    moderation_status = Column(String(50), default="approved")  # pending_review, approved, rejected, needs_edit

    # Source Tracking (for scraped data)
    source_id = Column(String(255), nullable=True, unique=True, index=True)  # External ID from source
    source_url = Column(String(1000), nullable=True)  # Original URL
    source_platform = Column(String(50), nullable=True)  # reddit, twitter, etc.

    # AI Analysis Fields (generated by AI)
    ai_analyzed = Column(Boolean, default=False)  # Whether AI has analyzed this
    ai_analyzed_at = Column(DateTime(timezone=True), nullable=True)
    ai_opportunity_score = Column(Integer, nullable=True)  # 0-100 AI-generated score
    ai_summary = Column(String(500), nullable=True)  # One-line AI insight for cards
    ai_market_size_estimate = Column(String(100), nullable=True)  # e.g., "$500M-$2B"
    ai_competition_level = Column(String(50), nullable=True)  # low, medium, high
    ai_urgency_level = Column(String(50), nullable=True)  # low, medium, high, critical
    ai_target_audience = Column(String(255), nullable=True)  # Primary target demographic
    ai_pain_intensity = Column(Integer, nullable=True)  # 1-10 scale
    ai_business_model_suggestions = Column(Text, nullable=True)  # JSON array of suggestions
    ai_competitive_advantages = Column(Text, nullable=True)  # JSON array of advantages
    ai_key_risks = Column(Text, nullable=True)  # JSON array of risks
    ai_next_steps = Column(Text, nullable=True)  # JSON array of recommended actions
    ai_generated_title = Column(String(500), nullable=True)  # AI-refined idea title
    ai_problem_statement = Column(Text, nullable=True)  # AI-generated problem statement
    
    # Raw source data (for user verification)
    raw_source_data = Column(Text, nullable=True)  # JSON of original scraped content

    # Census Demographics & Market Intelligence
    demographics = Column(JSONB, nullable=True)  # Census ACS data: population, income, age, education, etc.
    search_trends = Column(JSONB, nullable=True)  # Google Trends data at DMA level
    demographics_fetched_at = Column(DateTime(timezone=True), nullable=True)  # When demographic data was last fetched

    # Source Expansion — signal pipeline metadata
    confidence_tier = Column(String(20), nullable=True, index=True)  # goldmine | validated | weak_signal | noise
    contributing_sources = Column(JSONB, nullable=True)  # {"reddit": 3, "yelp": 1, "total_sources": 2}
    macro_context = Column(JSONB, nullable=True)  # {"unemployment_delta_90d": 0.18, "trend_direction": "rising"}

    # Timestamps
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

    # Relationships
    author = relationship("User", back_populates="opportunities")
    validations = relationship("Validation", back_populates="opportunity", cascade="all, delete-orphan")
    comments = relationship("Comment", back_populates="opportunity", cascade="all, delete-orphan")
    generated_reports = relationship("GeneratedReport", back_populates="opportunity")
    workspaces = relationship("UserWorkspace", back_populates="opportunity")
    enhanced_workspaces = relationship("EnhancedUserWorkspace", back_populates="opportunity")
    user_notes = relationship("OpportunityNote", back_populates="opportunity", cascade="all, delete-orphan")
    service_areas = relationship("ServiceAreaBoundary", back_populates="opportunity", cascade="all, delete-orphan")
    signals = relationship("OpportunitySignal", back_populates="opportunity")
    claim_limit_record = relationship("OpportunityClaimLimit", back_populates="opportunity", uselist=False, cascade="all, delete-orphan")
