import { useState } from 'react'
import { Download, Printer, Mail, Loader2, X, CheckCircle } from 'lucide-react'
import { useAuthStore } from '../../stores/authStore'

interface GeneratedReportViewerProps {
  report: {
    id: number
    title: string
    content: string
    report_type?: string
    confidence_score?: number
    created_at?: string
  }
}

export default function GeneratedReportViewer({ report }: GeneratedReportViewerProps) {
  const { token } = useAuthStore()
  const [exportingFormat, setExportingFormat] = useState<string | null>(null)
  const [showEmailModal, setShowEmailModal] = useState(false)
  const [emailAddress, setEmailAddress] = useState('')
  const [emailSending, setEmailSending] = useState(false)
  const [emailSuccess, setEmailSuccess] = useState(false)

  const headers = (): Record<string, string> => {
    const h: Record<string, string> = { 'Content-Type': 'application/json' }
    if (token) h['Authorization'] = `Bearer ${token}`
    return h
  }

  const handleExport = async (format: 'pdf' | 'docx') => {
    setExportingFormat(format)
    try {
      const res = await fetch(`/api/v1/reports/${report.id}/export/${format}`, { headers: headers() })
      if (!res.ok) throw new Error('Export failed')
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `OppGrid - ${report.title.slice(0, 60)}.${format}`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
    } catch (e) {
      console.error('Export failed:', e)
    } finally {
      setExportingFormat(null)
    }
  }

  const handlePrint = () => {
    const w = window.open('', '_blank')
    if (!w) return
    w.document.write(`
      <html>
      <head>
        <title>${report.title}</title>
        <style>
          body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
          h1 { color: #7c3aed; border-bottom: 2px solid #7c3aed; padding-bottom: 10px; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
        </style>
      </head>
      <body>
        <h1>${report.title}</h1>
        ${report.content}
        <div class="footer">Generated by OppGrid Intelligence Platform</div>
      </body>
      </html>
    `)
    w.document.close()
    w.print()
  }

  const handleSendEmail = async () => {
    if (!emailAddress) return
    setEmailSending(true)
    try {
      const res = await fetch('/api/v1/reports/send-email', {
        method: 'POST',
        headers: headers(),
        body: JSON.stringify({ report_id: report.id, email: emailAddress }),
      })
      if (res.ok) {
        setEmailSuccess(true)
        setTimeout(() => { setShowEmailModal(false); setEmailSuccess(false) }, 2000)
      }
    } catch (e) {
      console.error('Email failed:', e)
    } finally {
      setEmailSending(false)
    }
  }

  return (
    <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-amber-500 px-6 py-4">
        <h3 className="text-white font-bold text-lg">{report.title}</h3>
        {report.confidence_score && (
          <span className="text-white/80 text-sm">Confidence: {report.confidence_score}%</span>
        )}
      </div>

      {/* Content */}
      <div
        className="prose prose-sm max-w-none p-6 text-gray-700"
        dangerouslySetInnerHTML={{ __html: report.content }}
      />

      {/* Export bar */}
      <div className="border-t border-gray-200 px-6 py-4 flex flex-wrap items-center gap-3 bg-gray-50">
        <button
          onClick={() => handleExport('pdf')}
          disabled={exportingFormat === 'pdf'}
          className="flex items-center gap-2 px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600 text-sm font-medium disabled:opacity-50"
        >
          {exportingFormat === 'pdf' ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          PDF
        </button>
        <button
          onClick={() => handleExport('docx')}
          disabled={exportingFormat === 'docx'}
          className="flex items-center gap-2 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 text-sm font-medium disabled:opacity-50"
        >
          {exportingFormat === 'docx' ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          Word
        </button>
        <button
          onClick={handlePrint}
          className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-white text-sm font-medium"
        >
          <Printer className="w-4 h-4" />
          Print
        </button>
        <button
          onClick={() => setShowEmailModal(true)}
          className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg hover:bg-white text-sm font-medium"
        >
          <Mail className="w-4 h-4" />
          Email
        </button>
      </div>

      {/* Footer */}
      <div className="px-6 py-3 bg-gray-50 border-t border-gray-100 text-xs text-gray-400 flex items-center justify-between">
        <span>Generated by OppGrid Intelligence Platform</span>
        {report.created_at && <span>{new Date(report.created_at).toLocaleDateString()}</span>}
      </div>

      {/* Email modal */}
      {showEmailModal && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-md mx-4">
            <div className="flex items-center justify-between mb-4">
              <h4 className="font-semibold text-gray-900">Email Report</h4>
              <button onClick={() => setShowEmailModal(false)} className="text-gray-400 hover:text-gray-600">
                <X className="w-5 h-5" />
              </button>
            </div>
            {emailSuccess ? (
              <div className="flex items-center gap-2 text-green-600">
                <CheckCircle className="w-5 h-5" />
                <span>Report sent!</span>
              </div>
            ) : (
              <>
                <input
                  type="email"
                  value={emailAddress}
                  onChange={(e) => setEmailAddress(e.target.value)}
                  placeholder="recipient@example.com"
                  className="w-full p-3 border border-gray-200 rounded-lg mb-4 focus:ring-2 focus:ring-amber-500"
                />
                <button
                  onClick={handleSendEmail}
                  disabled={!emailAddress || emailSending}
                  className="w-full px-4 py-3 bg-amber-500 text-white rounded-lg hover:bg-amber-600 font-medium disabled:opacity-50"
                >
                  {emailSending ? 'Sending...' : 'Send Report'}
                </button>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
